web: PHP_CLI_SERVER_WORKERS=${PHP_CLI_SERVER_WORKERS:-8} php artisan serve --host=0.0.0.0 --port=${PORT:-8080}
worker: php artisan queue:work redis --sleep=1 --tries=3 --timeout=180 --memory=256 --queue=default
